require('dotenv').config({ path: '.env.local' });
const { GoogleGenerativeAI } = require('@google/generative-ai');

(async () => {
  try {
    const budget = 300;
    console.log('1. Fetching Zayka LLM...');
    const res = await fetch('https://consumption-awesome-kong-gore.trycloudflare.com/v1/completions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 
        prompt: 'Aap ek master Indian Chef ho (Zayka AI). Neeche diye gaye sawal ka best desi jawab do.\n\n### Instruction:\nBhai ek 300 rupees ke andar Indian student budget meal batao.\n\n### Output:\n',
        max_tokens: 400,
        stop: ['### Instruction', '</s>']
      })
    });
    if (!res.ok) throw new Error('Cloudflare Error: ' + res.status + ' ' + await res.text());
    
    const json = await res.json();
    const aiText = json.choices[0].text.trim();
    console.log('Zayka Response:', aiText.substring(0, 100) + '...');
    
    console.log('2. Parsing with Gemini...');
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error('Missing GEMINI_API_KEY locally!');
    
    const genAI = new GoogleGenerativeAI(apiKey);
    const parserModel = genAI.getGenerativeModel({ 
      model: 'gemini-1.5-flash',
      generationConfig: { responseMimeType: 'application/json' } 
    });
    
    const parserPrompt = 'You are a strict data parser. Read the following raw recipe generated by an Indian Chef AI. Extract the dish name, ingredients with costs, and format the cooking instructions step-by-step. The total budget was ?' + budget + '. Raw AI Text: ' + aiText + ' Return ONLY JSON matching this structure: { "dishName": "name", "totalCost": 50, "ingredients": [ {"name": "Item 1", "estimatedCost": 10} ], "quickRecipe": "Step 1: ...\\nStep 2: ..." }';
    
    const parserResult = await parserModel.generateContent(parserPrompt);
    const text = parserResult.response.text();
    console.log('Gemini Raw:', text);
    const parsedData = JSON.parse(text);
    console.log('SUCCESS!');
  } catch (err) {
    console.error('FAILED:', err);
  }
})();
