const fs = require('fs');

const fileLines = fs.readFileSync('src/lib/actions.ts', 'utf8').split('\n');
const topPart = fileLines.slice(0, 96).join('\n'); // 0 to 95

const bottomPart = \
export async function generateBudgetMealAction(budget: number, language: AppLanguage) {
  try {
    const prompt = \\\Aap ek master Indian Chef ho (Zayka AI). Neeche diye gaye sawal ka best desi jawab do.\\\\n\\\\n### Instruction:\\\\nBhai ek \\\ rupees ke andar Indian student budget meal batao.\\\\n\\\\n### Output:\\\\n\\\;

    const res = await fetch("https://consumption-awesome-kong-gore.trycloudflare.com/v1/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ 
        prompt: prompt,
        max_tokens: 350,
        stop: ["### Instruction", "</s>"]
      })
    });
    const json = await res.json();
    const aiText = json.choices[0].text.trim();
    
    // SMART PARSING: Zayka-LLM Native Parser
    const dishMatch = aiText.match(/version of (.*?), a classic/i) || aiText.match(/make a .*? (.*?)\\\\. You will/i);
    const dishName = dishMatch ? dishMatch[1].trim() : "Zayka Special Meal";
    
    const ingredientsMatch = aiText.match(/You will need:\\\\s*(.*?)\\\\.\\\\s*The secret/i);
    let ingredientsList: any[] = [];
    
    if (ingredientsMatch) {
      const items = ingredientsMatch[1].split(',');
      ingredientsList = items.map((item: any) => ({
        name: item.trim(),
        estimatedCost: Math.floor(budget / items.length)
      }));
    } else {
      ingredientsList = [{ name: "Zayka Ingredients", estimatedCost: budget }];
    }

    const recipeMatch = aiText.match(/The secret is.*?\\\\. (.*)/i);
    let rawRecipe = recipeMatch ? recipeMatch[1].trim() : aiText;
    
    const sentences = rawRecipe.split('. ').filter((s: string) => s.trim().length > 3);
    const formattedRecipe = sentences.map((s: string, i: number) => \\\Step \\\: \\\\\\).join('\\\\n');
    
    const data = {
      dishName: dishName,
      totalCost: ingredientsList.reduce((acc: any, curr: any) => acc + (curr.estimatedCost || 0), 0) || budget,
      ingredients: ingredientsList,
      quickRecipe: formattedRecipe
    };
    
    return { success: true, data };
  } catch (error: any) {
    console.error("Zayka Budget Error:", error);
    const errorMessage = error instanceof Error ? error.message : String(error);
    return { 
      success: true, 
      data: {
        dishName: "System Error!",
        totalCost: budget > 5 ? budget - 5 : budget,
        ingredients: [
          { name: "Poha (Flattened Rice)", estimatedCost: 20 },
          { name: "Peanuts & Curry Leaves", estimatedCost: 15 },
          { name: "Onion & Green Chilli", estimatedCost: 10 }
        ],
        quickRecipe: "Step 1: WE NEED TO DEBUG THIS.\\\\nStep 2: Exact Error: " + errorMessage
      }
    };
  }
}

export async function generateFusionRecipeAction(likedFoods: string[], language: AppLanguage) {
  try {
    const prompt = \\\Aap ek master Indian Chef ho (Zayka AI). Neeche diye gaye sawal ka best desi jawab do.\\\\n\\\\n### Instruction:\\\\n\\\ ka ek mast fusion dish batao.\\\\n\\\\n### Output:\\\\n\\\;

    const res = await fetch("https://consumption-awesome-kong-gore.trycloudflare.com/v1/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ 
        prompt: prompt,
        max_tokens: 350,
        stop: ["### Instruction", "</s>"]
      })
    });
    const json = await res.json();
    const aiText = json.choices[0].text.trim();
    
    const data = {
      name: "Zayka Fusion",
      tagline: "Custom fusion generated by Zayka LLM",
      emoji: "????",
      ingredients: likedFoods,
      instructions: aiText || "Fusion recipe text",
      time: "20 mins"
    };
    
    return { success: true, data };
  } catch (error: any) {
    console.error("Zayka Fusion Error:", error);
    return { 
      success: true, 
      data: {
        name: "Makhani Pizza ??",
        tagline: "A crispy thin Italian crust topped with rich Butter Chicken gravy.",
        emoji: "??????",
        ingredients: ["Pizza Base", "Butter Chicken Gravy", "Mozzarella Cheese", "Coriander"],
        instructions: "Step 1: Bake base for 5 mins.\\\\nStep 2: Spread makhani gravy.\\\\nStep 3: Top with cheese and bake.",
        time: "25 mins"
      } 
    };
  }
}
\;

fs.writeFileSync('src/lib/actions.ts', topPart + '\n' + bottomPart);
console.log('Fixed actions.ts');
