import { W } from '@/lib/theme';
import Link from 'next/link';

export default function TermsOfService() {
  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: '40px 24px', color: W.text, lineHeight: 1.6 }}>
      <Link href="/" style={{ color: W.primary, textDecoration: 'none', marginBottom: 24, display: 'inline-block' }}>&larr; Back to Home</Link>
      <h1 style={{ fontFamily: 'var(--font-playfair)', fontSize: 32, marginBottom: 24 }}>Terms of Service</h1>
      <p>Last updated: September 2026</p>
      
      <h2 style={{ marginTop: 24, fontSize: 20 }}>1. Acceptance of Terms</h2>
      <p>By using Zayka AI, you agree to these Terms. If you don't agree, please do not use the app.</p>
      
      <h2 style={{ marginTop: 24, fontSize: 20 }}>2. AI-Generated Content</h2>
      <p>Recipes and advice are generated by AI. We cannot guarantee perfect accuracy or safety (e.g., regarding allergies). Please use your own judgment and verify ingredients before cooking.</p>
      
      <h2 style={{ marginTop: 24, fontSize: 20 }}>3. User Conduct</h2>
      <p>Do not attempt to abuse the free AI API endpoints, reverse engineer the AR chef, or submit inappropriate content to family recipes.</p>
    </div>
  );
}
